# This is a basic workflow to help you get started with Actions

name: Santa-Secret

# Controls when the workflow will run
on:
   schedule:
      - cron:  '0 0 * * *' 
  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:  |
        
              curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh 
              postman login --with-api-key PMAK-64354cc863722677922671b6-e780c733d01a360b3a98e5fbebf94edd15
              postman collection run ""postman/collections/Santa box.json" -e "Santa prod.postman_environment.json" 
              postman collection run ""postman/collections/Santa change password.json" -e "Santa stage.postman_environment.json" -d "test-data.csv"
